//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace nlCrypto.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nlCrypto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [deCode]
        ///ab=A
        ///ad=B
        ///an=C
        ///at=D
        ///de=E
        ///do=F
        ///eo=G
        ///et=H
        ///ex=I
        ///in=J
        ///is=K
        ///ne=L
        ///ob=M
        ///si=N
        ///ut=O
        ///le=P
        ///la=Q
        ///ago=R
        ///aio=S
        ///amo=T
        ///aut=U
        ///cum=V
        ///cur=W
        ///diu=X
        ///duo=Y
        ///ego=Z
        ///fio=a
        ///hic=b
        ///huc=c
        ///iam=d
        ///ibi=e
        ///ita=f
        ///ius=g
        ///lex=h
        ///nam=i
        ///non=j
        ///nos=k
        ///nox=l
        ///num=m
        ///per=n
        ///pro=o
        ///qua=p
        ///que=q
        ///qui=r
        ///quo=s
        ///res=t
        ///rex=u
        ///rus=v
        ///sed=w
        ///sic=x
        ///sto=y
        ///sub=z
        ///sui=0
        ///sum=1
        ///tam=2
        ///tot=3
        ///tum=4
        ///ubi=5
        ///vel=6
        ///vir=7
        ///vis=8
        ///vix=9
        ///vos=+
        ///alo=/
        ///xd=&apos;
        ///aliquis=A
        ///alter=B
        ///annus=C
        ///ante=D
        ///appello=E
        ///aqua=F
        ///atque=G
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
    }
}
